#ifndef GUARD_CONSTANTS_HEXORB_H
#define GUARD_CONSTANTS_HEXORB_H

enum HexorbResultCodes
{
    HEXORB_RESULT_FAIL_TYPE_0,
    HEXORB_RESULT_FAIL_TYPE_1,
    HEXORB_RESULT_FAIL_FAINTED,
    HEXORB_RESULT_FAIL_HAS_STATUS,
    HEXORB_RESULT_FAIL_ABILITY,
    HEXORB_RESULT_SUCCESS,
    HEXORB_RESULT_COUNT,
};

#endif // GUARD_CONSTANTS_HEXORB_H